# Generated by Django 6.0.2 on 2026-02-08 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_company_logo_employee_salary_employee_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(default='Manual', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New Lead'), ('Busy', 'Busy / Call Later'), ('Interested', 'Highly Interested'), ('Not_Interested', 'Not Interested'), ('No_Response', 'No Response'), ('Enrolled', 'Enrolled')], default='New', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.employee')),
            ],
        ),
    ]
