# Generated by Django 6.0.2 on 2026-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New Lead'), ('Busy', 'Busy / Call Later'), ('Interested', 'Highly Interested'), ('Not_Interested', 'Not Interested'), ('No_Response', 'No Response'), ('Enrolled', 'Enrolled'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
    ]
