# Generated by Django 6.0.2 on 2026-02-08 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_lead_assigned_date_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_limit', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_batches', to='documents.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('task_docs_received', models.BooleanField(default=False)),
                ('task_research', models.BooleanField(default=False)),
                ('task_uni_list', models.BooleanField(default=False)),
                ('task_govt_scholarship', models.BooleanField(default=False)),
                ('task_prof_list', models.BooleanField(default=False)),
                ('task_cv', models.BooleanField(default=False)),
                ('task_email_draft', models.BooleanField(default=False)),
                ('task_email_sent', models.BooleanField(default=False)),
                ('task_sop_written', models.BooleanField(default=False)),
                ('task_sop_initial', models.BooleanField(default=False)),
                ('task_sop_final', models.BooleanField(default=False)),
                ('task_sop_program', models.BooleanField(default=False)),
                ('task_lor', models.BooleanField(default=False)),
                ('task_research_proposal', models.BooleanField(default=False)),
                ('task_portal_complete', models.BooleanField(default=False)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='documents.batch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
