# Generated by Django 6.0.2 on 2026-02-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_callrequest_supportticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_cv',
            new_name='task_apply',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_docs_received',
            new_name='task_docs',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_email_draft',
            new_name='task_sop',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_email_sent',
            new_name='task_visa',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_govt_scholarship',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_lor',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_portal_complete',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_prof_list',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_research_proposal',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_sop_final',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_sop_initial',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_sop_program',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_sop_written',
        ),
        migrations.RemoveField(
            model_name='enrolledclient',
            name='task_uni_list',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='resolved_at',
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolledclient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New Lead'), ('Busy', 'Busy / Call Later'), ('Interested', 'Highly Interested'), ('Not_Interested', 'Not Interested'), ('No_Response', 'No Response'), ('Enrolled', 'Enrolled')], default='New', max_length=20),
        ),
    ]
