# Generated by Django 6.0.2 on 2026-02-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_rename_task_cv_enrolledclient_task_apply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_apply',
            new_name='task_cv',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_docs',
            new_name='task_docs_received',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_sop',
            new_name='task_email_draft',
        ),
        migrations.RenameField(
            model_name='enrolledclient',
            old_name='task_visa',
            new_name='task_email_sent',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_govt_scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_lor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_portal_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_prof_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_research_proposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_sop_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_sop_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_sop_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_sop_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledclient',
            name='task_uni_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrolledclient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New Lead'), ('Busy', 'Busy / Call Later'), ('Interested', 'Highly Interested'), ('Not_Interested', 'Not Interested'), ('No_Response', 'No Response'), ('Enrolled', 'Enrolled'), ('Resolved', 'Resolved')], default='New', max_length=20),
        ),
    ]
